/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pacote.visao;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pacote.DAO.DAOMedico;
import pacote.dominio.Medico;

/**
 *
 * @author lies
 */
public class AlterarMedico extends javax.swing.JFrame {

    /**
     * Creates new form AlterarMedico
     */
    public AlterarMedico() {
        initComponents();
        DAOMedico dadosMedico = new DAOMedico();
        ArrayList<Medico> listaMedicos = new ArrayList();
        listaMedicos = dadosMedico.selecionarTodosRegistros();
        
        DefaultTableModel modelo = (DefaultTableModel) tabelaDadosMedico.getModel();
        
        for(Medico medico : listaMedicos){
            Object[] dados = {
                medico.getId(),
                medico.getCnpjCpf(),
                medico.getNome(),
                medico.getTipoPessoa(),
                medico.getTipoDocumento(),
                medico.getUf(),
                medico.getNumDocumento(),
                medico.getCidade(),
                medico.getCep(),
                medico.getEspecialidade(),
                medico.getEndereco(),
                medico.getBairro(),
                medico.getTelefone(),
                medico.getEmail()
            };
            modelo.addRow(dados);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaDadosMedico = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Farmácias 1.0");

        botaoVoltar.setBackground(new java.awt.Color(153, 153, 153));
        botaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        botaoVoltar.setText("VOLTAR");
        botaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVoltarActionPerformed(evt);
            }
        });

        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane2MouseClicked(evt);
            }
        });

        tabelaDadosMedico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "CNPJ_CPF", "NOME", "TIPO_PESSOA", "TIPO_DOCUMENTO", "UF", "NUM_DOCUMENTO", "CIDADE", "CEP", "ESPECIALIDADE", "ENDEREÇO", "BAIRRO", "TELEFONE", "E-MAIL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaDadosMedico.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaDadosMedicoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelaDadosMedico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1353, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoVoltar)
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(botaoVoltar)
                .addGap(23, 23, 23))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MenuInicial().setVisible(true);
    }//GEN-LAST:event_botaoVoltarActionPerformed

    private void tabelaDadosMedicoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaDadosMedicoMouseClicked
        // TODO add your handling code here:
        int resposta = JOptionPane.showConfirmDialog(null, "Deseja realmente atualizar esse registro?");

        if(resposta == 0){
            Medico medico = new Medico();

            int linha = tabelaDadosMedico.getSelectedRow();
            
            medico.setId(Integer.parseInt(tabelaDadosMedico.getValueAt(linha, 0).toString()));
            medico.setCnpjCpf(tabelaDadosMedico.getValueAt(linha, 1).toString());
            medico.setNome(tabelaDadosMedico.getValueAt(linha, 2).toString());
            medico.setTipoPessoa(tabelaDadosMedico.getValueAt(linha, 3).toString());
            medico.setTipoDocumento(tabelaDadosMedico.getValueAt(linha, 4).toString());
            medico.setUf(tabelaDadosMedico.getValueAt(linha, 5).toString());
            medico.setNumDocumento(tabelaDadosMedico.getValueAt(linha, 6).toString());
            medico.setCidade(tabelaDadosMedico.getValueAt(linha, 7).toString());
            medico.setCep(tabelaDadosMedico.getValueAt(linha, 8).toString());
            medico.setEspecialidade(tabelaDadosMedico.getValueAt(linha, 9).toString());
            medico.setEndereco(tabelaDadosMedico.getValueAt(linha, 10).toString());
            medico.setBairro(tabelaDadosMedico.getValueAt(linha, 11).toString());
            medico.setTelefone(tabelaDadosMedico.getValueAt(linha, 12).toString());
            medico.setEmail(tabelaDadosMedico.getValueAt(linha, 13).toString());
            
            new AlterarMedicoFormulario(medico).setVisible(true);
            dispose();
        }
    }//GEN-LAST:event_tabelaDadosMedicoMouseClicked

    private void jScrollPane2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlterarMedico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AlterarMedico().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoVoltar;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabelaDadosMedico;
    // End of variables declaration//GEN-END:variables
}
